# Generated by Django 2.2.4 on 2019-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about', models.SlugField(blank=True)),
                ('program', models.FileField(upload_to='programs/%Y/%m/%d/')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
