# Generated by Django 2.2.4 on 2019-09-10 21:51

from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.SlugField()),
                ('program', models.FileField(upload_to='programs/%Y/%m/%d/CppTests.cpp')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.IntegerField(unique=True)),
                ('typeOfProg', models.CharField(choices=[('file', 'File'), ('text', 'Text')], default='file', max_length=4)),
                ('typeOfLang', models.CharField(choices=[('c', 'C'), ('c++11', 'C++11'), ('c++14', 'C++14'), ('c++17', 'C++17'), ('python3', 'Python3')], default='c', max_length=10)),
                ('progInText', models.TextField()),
                ('progInFile', models.FileField(upload_to=review.models.userUploadFilePath)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cands', to='review.candidates')),
            ],
        ),
    ]
