# Generated by Django 2.2.4 on 2019-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190907_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='programText',
            field=models.SlugField(blank=True),
        ),
    ]
