# Generated by Django 2.2.4 on 2019-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_candidates_programtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='programText',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='program',
            field=models.FileField(upload_to='programs/%Y/%m/%d/CppTests.cpp'),
        ),
    ]
