# Generated by Django 2.2.4 on 2019-09-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telegram_contact', models.CharField(max_length=20)),
                ('about_candidate', models.TextField()),
                ('solved_quizez', models.FileField(upload_to='quizez/%Y/%m/%d/')),
                ('datetime_of_reqw', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
